@startuml

start
: 进入订单管理页面;

if (退房或者续住) is (退房) then
  :点击退房按钮;
  :弹出确认按钮;

  if (是否确认?) is (是) then
    :订单关闭;
    :退还押金;
  else (否)
  endif
else (续住)
    :点击续住按钮;
    if (是否确认?) is (是) then
        :更改退房时间;
      else (否)
      endif
endif
stop

@enduml
