@startuml
'https://plantuml.com/activity-diagram-beta

start
:点击个人中心;
:查看我的订单;
:选择预定的订单;
:跳转订单详情页面;
:点击退订;
:弹出确认窗口;
if (是否确认) then (是)
  :发送退订申请给管理员;
  :管理员审核退订申请;
  if (管理员是否同意?) then (是)
    :完成退订;
    else (否)
    :说明拒绝理由;
  endif
  :通知用户;
endif
stop

@enduml
