


@startuml
autonumber
actor 用户 as user
participant 青庭民宿网站 as client
control 订单控制器 as con
database 数据库 as data

user -> client : 选择客房，填写信息，下单
client -> client : 校验订单信息
client -> con : 发送订单信息
con -> con : 校验订单信息
con -> data : 保存订单信息
con --> client :返回下单成功消息
client --> user: 提示下单成功
client -> client : 跳转页面到我的订单页面
client -> con : 发送获取订单请求
con -> data : 获取订单请求
data --> con : 返回订单信息
con --> client : 返回订单数据
client --> user : 展示订单详情

@enduml