


@startuml
autonumber
actor 用户 as user
participant 青庭民宿网站 as client

actor 管理员 as admin
participant 青庭民宿管理系统 as server
control 订单控制器 as con
database 数据库 as data

user -> client : 选择订单，点击退订
client -> con : 发送请求
con -> data : 改变订单状态：退订中
con --> client : 返回请求结果，刷新页面
client --> user: 展示订单信息
con -> server : 发送退订申请消息
server --> admin : 提醒管理员
admin -> server: 审核通过
server -> con : 发送通过请求
con -> data : 订单状态：已退订

user -> client : 查看订单详情
client -> con : 发送查询请求
con -> data : 获取订单数据
data --> con : 返回订单数据
con --> client : 返回订单数据
client --> user : 展示订单状态



@enduml