server:
  port: 8010

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springgarden
      username: root
      password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.djq.springgarden.entity

logging:
  level:
    com.djq.springGarden: debug
# 分页框架
pagehelper:
  #指定数据库，可以不配置，pagehelper插件会自动检测数据库的类型。
  helperDialect: mysql
  #分页合理化参数默认false，当该参数设置为true 时，pageNum <= 0 时，默认显示第一页，pageNum 超过 pageSize 时，显示最后一页。
  reasonable: true
  #分页插件会根据查询方法的参数中，自动根据params 配置的字段中取值，找到合适的值会自动分页。　
  supportMethodsArguments: true
  #用于从对象中根据属性名取值，可以配置pageNum，pageSize，count 不用配置映射的默认值。
  params: count=countSql
